name: build-server

on:
  push:
    branches:
      - "main"
  # pull_request:
  #   branches:
  #     - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push if on main
        uses: docker/build-push-action@v5
        with:
          context: server
          file: server/Dockerfile
          push: true
          # push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tff-hackathon-ui:latest
